title: Matthew Ding's Post
theme: minima
image: https://ibb.co/60fmvrq 
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Matthew Ding's Final Website Project

# social links
twitter_username: none
github_username:  none

show_excerpts: true # set to false to remove excerpts on the homepage
