title: Matthew Ding's Post
theme: minima
author: GitHub User
email: mding@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  Matthew Ding's Final Website Project

# social links
twitter_username: Dontuse
github_username:  Md905908324

show_excerpts: true # set to false to remove excerpts on the homepage
